name: Publish docs
on:
  release:
    types:
    - published
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: pnpm/action-setup@v4
      with:
        run_install: true
    - run: |
        npx typedoc
    - uses: actions/upload-pages-artifact@v3
      with:
        path: _site
    - uses: actions/deploy-pages@v4
      id: deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
